### ISSUE TITLE
Naming of the method append to concatenate or merge

### ISSUE THREAD

**Issue by agy-why** [ekaterinailin/AltaiPony#46]
#### What needs to be created or improved?

In python naming a method `append` usually returns a modified version of the object, and not a modified copy. For this behavior the naming concatenate or merge is used.

#### Can you provide an example?

```python
a = [1, 2, 3]
a.append(4)
print(a)
>>> [1, 2, 3, 4]
```
`a` is modified.

```python
lc1.append(lc2)
```
`lc1` is not modified

#### What is the goal / expected behaviour?

```python
import copy

class A():
    
    def __init__(self, data):
        self.data = data
    
    def concatenate(self, other):
        '''This concatenate self.data and other.data into a new object'''
        merged = copy.deepcopy(self)
        merged.data += other.data
        return(merged)
    
    def append(self, other):
        '''This append other.data at the end of self.data.'''
        self.data += other.data
        return(True)
```

**Comment by ekaterinailin** [comment]
I decided not to offer the concatenation function anymore because

- de-trending is less costly on shorter light curve chunks, and
- injection-recovery sampling results should be interpreted with respect to individual light curves since their quality can vary across TESS/K2/Kepler sectors/campaigns/quarters
