### ISSUE TITLE
Can't use from_TargetPixel_source for short cadence Kepler data 

### ISSUE THREAD

**Issue by ceb8** [ekaterinailin/AltaiPony#49]
#### What needs to be created or improved?

`from_TargetPixel_source` seems to be the only way to get a lightcurve that is suitable for detrending, and it errors out on at least some short cadence inputs:

![image](https://user-images.githubusercontent.com/9406508/63114053-dbb02d80-bf61-11e9-8ead-cc8b5769da80.png)

I think this is because even with a given KID and quarter, there can still be multiple results from the call to `lightkurve.search_targetpixelfile()`.

#### Can you provide an example?

```python
from altaipony.lcio import from_TargetPixel_source
flc = from_TargetPixel_source("9592705", quarter=9, cadence='short')
```

#### What is the goal / expected behaviour?

I guess there needs to be a way to either load more than one target pixel file, or to allow the user to choose which one when there are more than one in a sector.

Alternately there could be a target pixel file counterpart to `from_KeplerLightCurve_file`, `from_KeplerTargetPixel_file` or something.

**Comment by ekaterinailin** [comment]
I hope that this problem is solved now. The file reading has changed quit a bit but should work like this:

`from altaipony.lcio import from_mast`
`flc = from_mast(9592705, c=5, cadence=short, mode="TPF", mission="Kepler")`

Let me know if that works for you. Note that you'll need the most recent version of AltaiPony for this.

**Comment by ceb8** [comment]
@ekaterinailin Yes! Thanks so much.
